include ./kitty-themes/tokyo-night-storm.conf

font_family JetBrainsMono Nerd Font
font_size 18
bold_font auto
italic_font auto
bold_italic_font auto
modify_font underline_position 3
modify_font underline_thickness 150%

background_opacity 0.60
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 1

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 0


selection_foreground none
selection_background none

foreground #dddddd
background #000000
cursor #dddddd

# Enable tabs
tab_bar_edge top
tab_bar_style powerline
tab_title_template "{index}: {title}"

# Colors
active_tab_font_style bold
active_tab_foreground #ffffff
active_tab_background #44475a
inactive_tab_foreground #bbbbbb
inactive_tab_background #2e3440
macos_option_as_alt yes
